// Code generated by `server_api plugin generate`; DO NOT EDIT.

package plugins

import (
	commonplugin "server_api/internal/common/plugin"
)

func generatedBuiltins() []commonplugin.Plugin {
	return []commonplugin.Plugin{}
}
