-- Database export: cf_backend_frame
-- Date: 2026-09-24 14:43:50
-- Generated by DBX

SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE `sys_dept` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `deleted_at` datetime(3) DEFAULT NULL,
  `name` varchar(64) COLLATE utf8mb4_general_ci NOT NULL COMMENT '部门名称',
  `parent_id` bigint unsigned NOT NULL DEFAULT '0' COMMENT '上级部门ID，0=顶级',
  `sort` int NOT NULL DEFAULT '0' COMMENT '排序',
  `leader` varchar(32) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '负责人',
  `remark` varchar(255) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '备注',
  PRIMARY KEY (`id`),
  KEY `idx_sys_dept_deleted_at` (`deleted_at`),
  KEY `idx_sys_dept_parent_id` (`parent_id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='部门表';

INSERT INTO `sys_dept` (`id`, `created_at`, `updated_at`, `deleted_at`, `name`, `parent_id`, `sort`, `leader`, `remark`) VALUES
(1, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '总公司', 0, 1, '张总', ''),
(2, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '技术部', 1, 1, '李工', ''),
(3, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '运营部', 1, 2, '王运营', ''),
(4, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '前端组', 2, 1, '', ''),
(5, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '后端组', 2, 2, '', '');

CREATE TABLE `sys_menu` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `deleted_at` datetime(3) DEFAULT NULL,
  `name` varchar(32) COLLATE utf8mb4_general_ci NOT NULL COMMENT '名称',
  `type` tinyint NOT NULL DEFAULT '2' COMMENT '1目录 2菜单 3按钮',
  `parent_id` bigint unsigned NOT NULL DEFAULT '0' COMMENT '上级ID，0=顶级',
  `path` varchar(128) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '前端路由地址',
  `api_path` varchar(255) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '后端接口，多个逗号分隔，如 POST:/admin/user/add',
  `icon` varchar(64) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '图标',
  `sort` int NOT NULL DEFAULT '0' COMMENT '排序',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '1显示 2隐藏',
  `remark` varchar(255) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '备注',
  PRIMARY KEY (`id`),
  KEY `idx_sys_menu_deleted_at` (`deleted_at`),
  KEY `idx_sys_menu_parent_id` (`parent_id`),
  KEY `idx_sys_menu_type` (`type`)
) ENGINE=InnoDB AUTO_INCREMENT=50 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='菜单/按钮表';

INSERT INTO `sys_menu` (`id`, `created_at`, `updated_at`, `deleted_at`, `name`, `type`, `parent_id`, `path`, `api_path`, `icon`, `sort`, `status`, `remark`) VALUES
(1, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '系统总览', 2, 0, '/dashboard', 'GET:/admin/dashboard/overview', 'Odometer', 1, 1, ''),
(2, '2026-09-23 16:51:28', '2026-09-23 21:40:55.523', NULL, '系统权限', 1, 0, '/system', '', 'Setting', 3, 1, ''),
(3, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '部门管理', 2, 2, '/system/dept', 'GET:/admin/dept/tree', 'OfficeBuilding', 1, 1, ''),
(4, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '部门新增', 3, 3, '', 'POST:/admin/dept/add', '', 1, 1, ''),
(5, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '部门修改', 3, 3, '', 'POST:/admin/dept/update', '', 2, 1, ''),
(6, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '部门删除', 3, 3, '', 'POST:/admin/dept/delete', '', 3, 1, ''),
(7, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '菜单管理', 2, 2, '/system/menu', 'GET:/admin/menu/list,GET:/admin/menu/tree', 'Menu', 2, 1, ''),
(8, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '菜单新增', 3, 7, '', 'POST:/admin/menu/add', '', 1, 1, ''),
(9, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '菜单修改', 3, 7, '', 'POST:/admin/menu/update', '', 2, 1, ''),
(10, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '菜单删除', 3, 7, '', 'POST:/admin/menu/delete', '', 3, 1, ''),
(11, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '角色管理', 2, 2, '/system/role', 'GET:/admin/role/list,GET:/admin/role/tree', 'UserFilled', 3, 1, ''),
(12, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '角色新增', 3, 11, '', 'POST:/admin/role/add', '', 1, 1, ''),
(13, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '角色修改', 3, 11, '', 'POST:/admin/role/update', '', 2, 1, ''),
(14, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '角色删除', 3, 11, '', 'POST:/admin/role/delete', '', 3, 1, ''),
(15, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '角色分配权限', 3, 11, '', 'POST:/admin/role/assign_menus', '', 4, 1, ''),
(16, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '人员管理', 2, 2, '/system/user', 'GET:/admin/user/list', 'User', 4, 1, ''),
(17, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '用户新增', 3, 16, '', 'POST:/admin/user/add', '', 1, 1, ''),
(18, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '用户修改', 3, 16, '', 'POST:/admin/user/update', '', 2, 1, ''),
(19, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '用户删除', 3, 16, '', 'POST:/admin/user/delete', '', 3, 1, ''),
(20, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '重置密码', 3, 16, '', 'POST:/admin/user/reset_password', '', 4, 1, ''),
(21, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '踢用户下线', 3, 16, '', 'POST:/admin/user/kick', '', 5, 1, ''),
(22, '2026-09-23 16:51:28', '2026-09-23 21:40:49.271', NULL, '系统配置', 1, 0, '/config', '', 'Tools', 2, 1, ''),
(23, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '渠道配置', 1, 22, '/config/channel', '', 'Connection', 1, 1, ''),
(24, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '存储配置', 2, 23, '/config/channel/storage', 'GET:/admin/storage/list', 'Box', 1, 1, ''),
(25, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '存储新增', 3, 24, '', 'POST:/admin/storage/add', '', 1, 1, ''),
(26, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '存储修改', 3, 24, '', 'POST:/admin/storage/update', '', 2, 1, ''),
(27, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '存储删除', 3, 24, '', 'POST:/admin/storage/delete', '', 3, 1, ''),
(28, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '存储设为默认', 3, 24, '', 'POST:/admin/storage/set_default', '', 4, 1, ''),
(29, '2026-09-23 16:51:28', '2026-09-23 16:54:12.491', NULL, '系统维护', 1, 0, '/maintain', '', 'Coin', 4, 1, ''),
(30, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '日志维护', 1, 29, '/maintain/log', '', 'Document', 1, 1, ''),
(31, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '操作日志', 2, 30, '/maintain/log/operation', 'GET:/admin/log/operation/list', 'List', 1, 1, ''),
(32, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '短信配置', 2, 23, '/config/channel/sms', 'GET:/admin/sms/config/list,GET:/admin/sms/signature/list,GET:/admin/sms/template/list,GET:/admin/sms/log/list', 'ChatDotRound', 2, 1, ''),
(33, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '短信开发配置保存', 3, 32, '', 'POST:/admin/sms/config/save', '', 1, 1, ''),
(34, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '短信开发配置删除', 3, 32, '', 'POST:/admin/sms/config/delete', '', 2, 1, ''),
(35, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '短信签名保存', 3, 32, '', 'POST:/admin/sms/signature/save', '', 3, 1, ''),
(36, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '短信签名删除', 3, 32, '', 'POST:/admin/sms/signature/delete', '', 4, 1, ''),
(37, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '短信模板保存', 3, 32, '', 'POST:/admin/sms/template/save', '', 5, 1, ''),
(38, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '短信模板删除', 3, 32, '', 'POST:/admin/sms/template/delete', '', 6, 1, ''),
(39, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '微信配置', 2, 23, '/config/channel/wechat', 'GET:/admin/wechat/config/list', 'ChatLineRound', 3, 1, ''),
(40, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '微信配置保存', 3, 39, '', 'POST:/admin/wechat/config/save', '', 1, 1, ''),
(41, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '微信配置删除', 3, 39, '', 'POST:/admin/wechat/config/delete', '', 2, 1, ''),
(42, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '支付配置', 2, 23, '/config/channel/payment', 'GET:/admin/payment/config/list', 'Wallet', 4, 1, ''),
(43, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '支付配置保存', 3, 42, '', 'POST:/admin/payment/config/save', '', 1, 1, ''),
(44, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '支付配置删除', 3, 42, '', 'POST:/admin/payment/config/delete', '', 2, 1, ''),
(45, '2026-09-23 21:36:59.754', '2026-09-23 21:36:59.754', NULL, '平台配置', 1, 22, '', '', 'SetUp', 10, 1, '管理各端平台基础信息'),
(46, '2026-09-23 21:36:59.758', '2026-09-23 21:36:59.758', NULL, '管理端配置', 2, 45, '/config/platform/admin', 'GET:/admin/platform/admin/detail', 'Monitor', 1, 1, '管理端Logo与系统名称'),
(47, '2026-09-23 21:36:59.761', '2026-09-23 21:36:59.761', NULL, '用户端配置', 2, 45, '/config/platform/user', 'GET:/admin/platform/user/detail', 'UserFilled', 2, 1, '用户默认昵称与头像'),
(48, '2026-09-23 21:36:59.766', '2026-09-23 21:36:59.766', NULL, '保存管理端配置', 3, 46, '', 'POST:/admin/platform/admin/save', '', 1, 1, '保存管理端平台配置'),
(49, '2026-09-23 21:36:59.768', '2026-09-23 21:36:59.768', NULL, '保存用户端配置', 3, 47, '', 'POST:/admin/platform/user/save', '', 1, 1, '保存用户端平台配置');

CREATE TABLE `sys_operation_log` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `user_id` bigint unsigned DEFAULT NULL,
  `username` varchar(32) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `method` varchar(16) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `path` varchar(128) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `request_params` mediumtext COLLATE utf8mb4_general_ci,
  `response_params` mediumtext COLLATE utf8mb4_general_ci,
  `ip` varchar(64) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `user_agent` varchar(255) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `code` int NOT NULL DEFAULT '0',
  `cost_ms` bigint NOT NULL DEFAULT '0',
  `client` varchar(16) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `idx_sys_operation_log_user_id` (`user_id`),
  KEY `idx_sys_operation_log_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='用户操作日志表';

CREATE TABLE `sys_payment_config` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `deleted_at` datetime(3) DEFAULT NULL,
  `name` varchar(64) COLLATE utf8mb4_general_ci NOT NULL,
  `channel` tinyint NOT NULL COMMENT '1微信支付 2支付宝',
  `app_id` varchar(128) COLLATE utf8mb4_general_ci NOT NULL,
  `merchant_id` varchar(128) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `private_key` text COLLATE utf8mb4_general_ci,
  `public_key` text COLLATE utf8mb4_general_ci,
  `api_v3_key` varchar(255) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `cert_serial_no` varchar(128) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `notify_url` varchar(500) COLLATE utf8mb4_general_ci NOT NULL,
  `status` tinyint NOT NULL DEFAULT '1',
  `sort` int NOT NULL DEFAULT '0',
  `remark` varchar(255) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `idx_sys_payment_config_deleted_at` (`deleted_at`),
  KEY `idx_sys_payment_config_channel` (`channel`),
  KEY `idx_sys_payment_config_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='支付渠道配置';

CREATE TABLE `sys_platform_config` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `created_at` datetime(3) DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime(3) DEFAULT NULL COMMENT '更新时间',
  `deleted_at` datetime(3) DEFAULT NULL COMMENT '删除时间',
  `type` tinyint unsigned NOT NULL COMMENT '平台类型，1管理端，2用户端',
  `logo` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '管理端Logo相对路径',
  `system_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '管理端系统名称',
  `default_nickname` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '用户端默认昵称',
  `default_avatar` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '用户端默认头像相对路径',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_platform_type` (`type`),
  KEY `idx_sys_platform_config_deleted_at` (`deleted_at`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='平台基础配置表';

INSERT INTO `sys_platform_config` (`id`, `created_at`, `updated_at`, `deleted_at`, `type`, `logo`, `system_name`, `default_nickname`, `default_avatar`) VALUES
(1, '2026-09-23 21:36:59.591', '2026-09-23 21:38:24.348', NULL, 1, 'uploads/2026/09/23/7ebe1037451fcc1546d7dd2662dde803.png', '后台管理系统', '', ''),
(2, '2026-09-23 21:36:59.659', '2026-09-23 21:38:39.412', NULL, 2, '', '', '用户', 'uploads/2026/09/23/7ebe1037451fcc1546d7dd2662dde803.png');

CREATE TABLE `sys_role` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `deleted_at` datetime(3) DEFAULT NULL,
  `name` varchar(32) COLLATE utf8mb4_general_ci NOT NULL COMMENT '角色名称',
  `code` varchar(32) COLLATE utf8mb4_general_ci NOT NULL COMMENT '角色编码',
  `parent_id` bigint unsigned NOT NULL DEFAULT '0' COMMENT '上级角色ID，0=顶级',
  `sort` int NOT NULL DEFAULT '0' COMMENT '排序',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '1启用 2禁用',
  `remark` varchar(255) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_role_code` (`code`),
  KEY `idx_sys_role_deleted_at` (`deleted_at`),
  KEY `idx_sys_role_parent_id` (`parent_id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='角色表';

INSERT INTO `sys_role` (`id`, `created_at`, `updated_at`, `deleted_at`, `name`, `code`, `parent_id`, `sort`, `status`, `remark`) VALUES
(1, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '总经理', 'ceo', 0, 1, 1, '顶级角色'),
(2, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '系统管理员', 'sys_admin', 1, 1, 1, '负责系统权限配置'),
(3, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '运营管理', 'op_manager', 1, 2, 1, '运营负责人'),
(4, '2026-09-23 16:51:28', '2026-09-23 16:51:28', NULL, '运营专员', 'op_staff', 3, 1, 1, '普通运营');

CREATE TABLE `sys_role_menu` (
  `role_id` bigint unsigned NOT NULL,
  `menu_id` bigint unsigned NOT NULL,
  PRIMARY KEY (`role_id`,`menu_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='角色-菜单关联';

INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES
(2, 1),
(2, 2),
(2, 3),
(2, 4),
(2, 5),
(2, 6),
(2, 7),
(2, 8),
(2, 9),
(2, 10),
(2, 11),
(2, 12),
(2, 13),
(2, 14),
(2, 15),
(2, 16),
(2, 17),
(2, 18),
(2, 19),
(2, 20),
(2, 21),
(2, 22),
(2, 23),
(2, 24),
(2, 25),
(2, 26),
(2, 27),
(2, 28),
(2, 29),
(2, 30),
(2, 31),
(2, 32),
(2, 33),
(2, 34),
(2, 35),
(2, 36),
(2, 37),
(2, 38),
(2, 39),
(2, 40),
(2, 41),
(2, 42),
(2, 43),
(2, 44),
(2, 45),
(2, 46),
(2, 47),
(2, 48),
(2, 49),
(4, 1);

CREATE TABLE `sys_sms_config` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `deleted_at` datetime(3) DEFAULT NULL,
  `name` varchar(64) COLLATE utf8mb4_general_ci NOT NULL,
  `provider` tinyint NOT NULL COMMENT '1阿里云 2腾讯云',
  `access_key_id` varchar(128) COLLATE utf8mb4_general_ci NOT NULL,
  `access_key_secret` varchar(255) COLLATE utf8mb4_general_ci NOT NULL,
  `endpoint` varchar(255) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `status` tinyint NOT NULL DEFAULT '1',
  `remark` varchar(255) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `idx_sys_sms_config_deleted_at` (`deleted_at`),
  KEY `idx_sys_sms_config_provider` (`provider`),
  KEY `idx_sys_sms_config_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='短信开发配置';

CREATE TABLE `sys_sms_send_log` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `config_id` bigint unsigned NOT NULL,
  `signature_id` bigint unsigned NOT NULL DEFAULT '0',
  `template_id` bigint unsigned NOT NULL DEFAULT '0',
  `mobile` varchar(32) COLLATE utf8mb4_general_ci NOT NULL,
  `content` varchar(1000) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `status` tinyint NOT NULL COMMENT '1待发送 2成功 3失败',
  `provider_message_id` varchar(128) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `error_message` varchar(500) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `sent_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_sys_sms_send_log_config_id` (`config_id`),
  KEY `idx_sys_sms_send_log_mobile` (`mobile`),
  KEY `idx_sys_sms_send_log_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='短信发送记录';

CREATE TABLE `sys_sms_signature` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `deleted_at` datetime(3) DEFAULT NULL,
  `config_id` bigint unsigned NOT NULL,
  `name` varchar(64) COLLATE utf8mb4_general_ci NOT NULL,
  `sign_code` varchar(128) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `status` tinyint NOT NULL DEFAULT '1',
  `remark` varchar(255) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `idx_sys_sms_signature_deleted_at` (`deleted_at`),
  KEY `idx_sys_sms_signature_config_id` (`config_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='短信签名';

CREATE TABLE `sys_sms_template` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `deleted_at` datetime(3) DEFAULT NULL,
  `config_id` bigint unsigned NOT NULL,
  `name` varchar(64) COLLATE utf8mb4_general_ci NOT NULL,
  `template_code` varchar(128) COLLATE utf8mb4_general_ci NOT NULL,
  `type` tinyint NOT NULL COMMENT '1验证码 2通知 3营销',
  `content` varchar(500) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `status` tinyint NOT NULL DEFAULT '1',
  `remark` varchar(255) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `idx_sys_sms_template_deleted_at` (`deleted_at`),
  KEY `idx_sys_sms_template_config_id` (`config_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='短信模板';

CREATE TABLE `sys_storage_config` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `deleted_at` datetime(3) DEFAULT NULL,
  `name` varchar(64) COLLATE utf8mb4_general_ci NOT NULL COMMENT '渠道名称',
  `channel` varchar(32) COLLATE utf8mb4_general_ci NOT NULL COMMENT '渠道类型: local/alioss/cos/qiniu/minio',
  `params` text COLLATE utf8mb4_general_ci COMMENT '渠道参数JSON',
  `is_default` tinyint NOT NULL DEFAULT '0' COMMENT '1默认渠道',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '1启用 2禁用',
  `sort` int NOT NULL DEFAULT '0' COMMENT '排序',
  `remark` varchar(255) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '备注',
  `default_slot` tinyint GENERATED ALWAYS AS ((case when ((`deleted_at` is null) and (`is_default` = 1)) then 1 else NULL end)) STORED COMMENT '保证全局至多一个有效默认渠道',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_storage_default_slot` (`default_slot`),
  KEY `idx_sys_storage_config_deleted_at` (`deleted_at`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='文件存储渠道配置表';

INSERT INTO `sys_storage_config` (`id`, `created_at`, `updated_at`, `deleted_at`, `name`, `channel`, `params`, `is_default`, `status`, `sort`, `remark`) VALUES
(1, '2026-09-23 16:51:28', '2026-09-23 22:40:41.574', NULL, '本地存储', 'local', '{"root_path":"./uploads"}', 0, 1, 1, '默认本地文件存储'),
(3, '2026-09-23 21:28:34.833', '2026-09-23 22:40:41.575', NULL, '七牛云oss存储', 'qiniu', '{"bucket":"","access_key":"YWwjHxwQ2","secret_key":"AfkAR7qrMo8iVx","domain":"https://cdn.utudati.com"}', 1, 1, 0, '');

CREATE TABLE `sys_upload_file` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `file_name` varchar(255) COLLATE utf8mb4_general_ci NOT NULL COMMENT '原始文件名',
  `hash_name` varchar(128) COLLATE utf8mb4_general_ci NOT NULL COMMENT '平台hash名(md5+扩展名)',
  `size` bigint NOT NULL DEFAULT '0' COMMENT '文件大小(字节)',
  `mime_type` varchar(128) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '文件类型(MIME)',
  `ext` varchar(32) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '文件扩展名',
  `client` varchar(16) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '来源: admin/api',
  `relative_path` varchar(512) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '文件相对路径(云端为对象Key)',
  `absolute_path` varchar(1024) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '文件绝对路径(云端为完整访问URL)',
  `uploader_id` bigint unsigned DEFAULT NULL COMMENT '上传人ID(可空)',
  PRIMARY KEY (`id`),
  KEY `idx_sys_upload_file_hash_name` (`hash_name`),
  KEY `idx_sys_upload_file_uploader_id` (`uploader_id`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='上传文件记录表';

INSERT INTO `sys_upload_file` (`id`, `created_at`, `updated_at`, `file_name`, `hash_name`, `size`, `mime_type`, `ext`, `client`, `relative_path`, `absolute_path`, `uploader_id`) VALUES
(1, '2026-09-23 18:39:25.429', '2026-09-23 18:39:25.429', 'user_avatar2.jpeg', '621f441cce2a461a4818f3cb67ef4494.jpeg', 21050, 'image/jpeg', 'jpeg', 'admin', 'uploads/2026/09/23/621f441cce2a461a4818f3cb67ef4494.jpeg', '/files/uploads/2026/09/23/621f441cce2a461a4818f3cb67ef4494.jpeg', 1),
(2, '2026-09-23 18:39:40.279', '2026-09-23 18:39:40.279', 'user_avatar1.png', '7ebe1037451fcc1546d7dd2662dde803.png', 43945, 'image/png', 'png', 'admin', 'uploads/2026/09/23/7ebe1037451fcc1546d7dd2662dde803.png', '/files/uploads/2026/09/23/7ebe1037451fcc1546d7dd2662dde803.png', 1),
(3, '2026-09-23 21:38:23.047', '2026-09-23 21:38:23.047', 'user_avatar1.png', '7ebe1037451fcc1546d7dd2662dde803.png', 43945, 'image/png', 'png', 'admin', 'uploads/2026/09/23/7ebe1037451fcc1546d7dd2662dde803.png', 'https://cdn.image.tutudati.com/uploads/2026/09/23/7ebe1037451fcc1546d7dd2662dde803.png', 1),
(4, '2026-09-23 21:38:37.997', '2026-09-23 21:38:37.997', 'user_avatar1.png', '7ebe1037451fcc1546d7dd2662dde803.png', 43945, 'image/png', 'png', 'admin', 'uploads/2026/09/23/7ebe1037451fcc1546d7dd2662dde803.png', 'https://cdn.image.tutudati.com/uploads/2026/09/23/7ebe1037451fcc1546d7dd2662dde803.png', 1),
(5, '2026-09-23 21:38:46.821', '2026-09-23 21:38:46.821', 'user_avatar1.png', '7ebe1037451fcc1546d7dd2662dde803.png', 43945, 'image/png', 'png', 'admin', 'uploads/2026/09/23/7ebe1037451fcc1546d7dd2662dde803.png', 'https://cdn.image.tutudati.com/uploads/2026/09/23/7ebe1037451fcc1546d7dd2662dde803.png', 1),
(6, '2026-09-23 21:38:56.754', '2026-09-23 21:38:56.754', 'user_avatar1.png', '7ebe1037451fcc1546d7dd2662dde803.png', 43945, 'image/png', 'png', 'admin', 'uploads/2026/09/23/7ebe1037451fcc1546d7dd2662dde803.png', 'https://cdn.image.tutudati.com/uploads/2026/09/23/7ebe1037451fcc1546d7dd2662dde803.png', 1),
(7, '2026-09-23 21:52:34.154', '2026-09-23 21:52:34.154', 'user_avatar1.png', '7ebe1037451fcc1546d7dd2662dde803.png', 43945, 'image/png', 'png', 'admin', 'uploads/2026/09/23/7ebe1037451fcc1546d7dd2662dde803.png', 'https://cdn.image.tutudati.com/uploads/2026/09/23/7ebe1037451fcc1546d7dd2662dde803.png', 1);

CREATE TABLE `sys_user` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `deleted_at` datetime(3) DEFAULT NULL,
  `username` varchar(32) COLLATE utf8mb4_general_ci NOT NULL COMMENT '登录名',
  `password` varchar(128) COLLATE utf8mb4_general_ci NOT NULL COMMENT 'bcrypt密文',
  `nickname` varchar(32) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '姓名',
  `avatar` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '头像相对路径',
  `mobile` varchar(16) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '手机号',
  `email` varchar(64) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '邮箱',
  `dept_id` bigint unsigned NOT NULL DEFAULT '0' COMMENT '所属部门',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '1启用 2禁用',
  `is_super` tinyint NOT NULL DEFAULT '0' COMMENT '1超级管理员',
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`),
  KEY `idx_sys_user_deleted_at` (`deleted_at`),
  KEY `idx_sys_user_dept_id` (`dept_id`),
  KEY `idx_sys_user_status` (`status`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='用户表';

INSERT INTO `sys_user` (`id`, `created_at`, `updated_at`, `deleted_at`, `username`, `password`, `nickname`, `avatar`, `mobile`, `email`, `dept_id`, `status`, `is_super`) VALUES
(1, '2026-09-23 16:51:28', '2026-09-23 21:38:57.373', NULL, 'admin', '$2a$10$xBQeertsN46doGwzCyVFx.sJ51JOtSvntXzdv5PMmucSXWZEXfxoe', '超级管理员', 'uploads/2026/09/23/7ebe1037451fcc1546d7dd2662dde803.png', '13800000001', 'admin@example.com', 5, 1, 1),
(2, '2026-09-23 16:51:28', '2026-09-23 21:52:35.466', NULL, 'zhangsan', '$2a$10$xBQeertsN46doGwzCyVFx.sJ51JOtSvntXzdv5PMmucSXWZEXfxoe', '张三', 'uploads/2026/09/23/7ebe1037451fcc1546d7dd2662dde803.png', '13800000002', 'zhangsan@example.com', 3, 1, 0);

CREATE TABLE `sys_user_login` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `login_id` varchar(64) COLLATE utf8mb4_general_ci NOT NULL COMMENT '登录唯一标识(uuid)',
  `user_id` bigint unsigned NOT NULL COMMENT '用户ID',
  `username` varchar(32) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '登录名',
  `client` varchar(16) COLLATE utf8mb4_general_ci DEFAULT '' COMMENT 'admin/api',
  `login_ip` varchar(64) COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '登录IP',
  `user_agent` varchar(255) COLLATE utf8mb4_general_ci DEFAULT '' COMMENT 'UA',
  `login_at` datetime(3) DEFAULT NULL COMMENT '登录时间',
  `logout_at` datetime(3) DEFAULT NULL COMMENT '退出时间',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '1在线 2已退出 3被踢下线',
  PRIMARY KEY (`id`),
  UNIQUE KEY `login_id` (`login_id`),
  KEY `idx_sys_user_login_user_id` (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='登录流水表';

INSERT INTO `sys_user_login` (`id`, `login_id`, `user_id`, `username`, `client`, `login_ip`, `user_agent`, `login_at`, `logout_at`, `status`) VALUES
(1, 'ac5a893c-ee5a-46ab-a787-80677b9a3caf', 1, 'admin', 'admin', '127.0.0.1', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:156.0) Gecko/20100101 Firefox/156.0', '2026-09-23 16:54:30.302', '2026-09-23 16:54:43.172', 2),
(2, '452a0193-6542-4496-816c-72b9fdd1e8c2', 1, 'admin', 'admin', '127.0.0.1', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:156.0) Gecko/20100101 Firefox/156.0', '2026-09-23 16:54:49.641', '2026-09-23 16:57:38.512', 2),
(3, '4188390b-c4ef-4d99-813f-508fc05831cb', 1, 'admin', 'admin', '127.0.0.1', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:156.0) Gecko/20100101 Firefox/156.0', '2026-09-23 16:57:42.499', '2026-09-23 18:40:45.804', 2),
(4, 'd0b7dbcd-8024-4b0c-bffa-2f6cde03c1b8', 1, 'admin', 'admin', '127.0.0.1', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:156.0) Gecko/20100101 Firefox/156.0', '2026-09-23 18:44:13.127', '2026-09-23 18:44:19.516', 2),
(5, 'ffaed5ad-901d-4adf-abed-b395a10e1499', 1, 'admin', 'admin', '127.0.0.1', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:156.0) Gecko/20100101 Firefox/156.0', '2026-09-23 18:44:33.921', NULL, 1),
(6, 'bd46cb42-b8bf-4762-935d-03929b2bae18', 1, 'admin', 'admin', '127.0.0.1', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:156.0) Gecko/20100101 Firefox/156.0', '2026-09-23 20:55:11.708', '2026-09-23 21:17:51.200', 2),
(7, '2ce448d3-1268-4962-9ded-b0356f524302', 1, 'admin', 'admin', '127.0.0.1', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:156.0) Gecko/20100101 Firefox/156.0', '2026-09-23 21:22:27.624', '2026-09-23 21:39:09.761', 2),
(8, 'cc6fd2b0-cf56-4053-88ab-e282ab60cfc7', 1, 'admin', 'admin', '127.0.0.1', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:156.0) Gecko/20100101 Firefox/156.0', '2026-09-23 21:39:31.691', '2026-09-23 23:00:30.059', 2);

CREATE TABLE `sys_user_role` (
  `user_id` bigint unsigned NOT NULL,
  `role_id` bigint unsigned NOT NULL,
  PRIMARY KEY (`user_id`,`role_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='用户-角色关联';

INSERT INTO `sys_user_role` (`user_id`, `role_id`) VALUES (2, 4);

CREATE TABLE `sys_wechat_config` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `deleted_at` datetime(3) DEFAULT NULL,
  `name` varchar(64) COLLATE utf8mb4_general_ci NOT NULL,
  `type` tinyint NOT NULL COMMENT '1公众号 2开放平台 3小程序',
  `app_id` varchar(128) COLLATE utf8mb4_general_ci NOT NULL,
  `app_secret` varchar(255) COLLATE utf8mb4_general_ci NOT NULL,
  `token` varchar(255) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `aes_key` varchar(255) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `status` tinyint NOT NULL DEFAULT '1',
  `remark` varchar(255) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_wechat_config_app_id` (`app_id`),
  KEY `idx_sys_wechat_config_deleted_at` (`deleted_at`),
  KEY `idx_sys_wechat_config_type` (`type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='微信应用配置';

SET FOREIGN_KEY_CHECKS = 1;
