package plugininstaller

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// GenerateRegistry 扫描 internal/plugins 子目录并生成静态插件注册文件。
func GenerateRegistry(serverRoot string) error {
	pluginsDir := filepath.Join(serverRoot, "internal", "plugins")
	entries, err := os.ReadDir(pluginsDir)
	if err != nil {
		return fmt.Errorf("读取插件目录失败: %w", err)
	}
	ids := make([]string, 0)
	for _, entry := range entries {
		if !entry.IsDir() || !keyPattern.MatchString(entry.Name()) {
			continue
		}
		if _, err := os.Stat(filepath.Join(pluginsDir, entry.Name(), "plugin.go")); err == nil {
			ids = append(ids, entry.Name())
		}
	}
	sort.Strings(ids)
	var builder strings.Builder
	builder.WriteString("// Code generated by `server_api plugin generate`; DO NOT EDIT.\n\npackage plugins\n\nimport (\n")
	builder.WriteString("\tcommonplugin \"server_api/internal/common/plugin\"\n")
	for _, id := range ids {
		fmt.Fprintf(&builder, "\tplugin_%s \"server_api/internal/plugins/%s\"\n", id, id)
	}
	builder.WriteString(")\n\nfunc generatedBuiltins() []commonplugin.Plugin {\n\treturn []commonplugin.Plugin{\n")
	for _, id := range ids {
		fmt.Fprintf(&builder, "\t\tplugin_%s.New(),\n", id)
	}
	builder.WriteString("\t}\n}\n")
	formatted, err := format.Source([]byte(builder.String()))
	if err != nil {
		return fmt.Errorf("生成插件注册代码失败: %w", err)
	}
	return os.WriteFile(filepath.Join(pluginsDir, "register_gen.go"), formatted, 0o644)
}
